### ISSUE TITLE
Feature Request:  Dropdown mentu & Multilingual site

### ISSUE THREAD

**Issue by rokib-rajon** [stackbit-themes/diy-unibit#2]
I found no way to implement multilingual functionality and dropdown menu feature.

**Comment by smnh** [comment]
Hi @rokib-rajon,

Unibit doesn't support Multilingual sites.
I suggest using Hugo or Gatsby + Contentful directly to make multilingual Jamstack sites.

**Comment by rokib-rajon** [comment]
@smnh Can I use this DIY as gatsby theme?

**Comment by smnh** [comment]
@rokib-rajon yes, click "create with stackbit" button in readme file. Then in Stackbit, change SSG to Gatsby and CMS to Contentful. Stackbit will generate a Gatsby version of that theme and provision a Contentful space for you. Then you will need to update the Contentful space to be multilingual and update the code of the generated Gatsby site to handle locales.

**Comment by rokib-rajon** [comment]
@smnh Can you guide me ? I have little knowledge about coding. I have done the contentful part but can not understand where to change the code in Gatsby.

**Comment by youvalv** [comment]
Hi @rokib-rajon!

Our support does not involve step-by-step guides for coding, you can find those in various places on the internet, and specifically with Gatsby documentation.

Good luck!

Youval
